In [1]:
import os
os.getcwd()

'C:\\Users\\ASUS TUF'

In [2]:
import os
os.listdir(".")

['-1.14-windows.xml',
 '.anaconda',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.copilot',
 '.docker',
 '.eclipse',
 '.emulator_console_auth_token',
 '.gemini',
 '.git',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.Ld9VirtualBox',
 '.lesshst',
 '.local',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.ollama',
 '.openjfx',
 '.p2',
 '.packettracer',
 '.redhat',
 '.skiko',
 '.streamlit',
 '.viminfo',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 'airflow',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'C',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'downloadtemp',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'gabung_modis_2019_2024.ipynb',
 'int main(){.c',
 'int main(){.cpp',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TM.blf',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'output',
 'Pictures',
 'pipx',
 'Postman',
 'PRAK001_2310817310014_MUHAMMADRIZKISAPUTRA.py',
 "print('Hello World').py",
 "print('Muhammad Rizki Saputra_2310817310014').py",
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Tugas_Praktikum_Pemprogramman',
 'Ubisoft Game Launcher',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Videos',
 'VirtualBox VMs',
 'WPS Cloud Files']

In [3]:
os.listdir("data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [4]:
import os
os.getcwd()
os.listdir(".")

['-1.14-windows.xml',
 '.anaconda',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.copilot',
 '.docker',
 '.eclipse',
 '.emulator_console_auth_token',
 '.gemini',
 '.git',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.Ld9VirtualBox',
 '.lesshst',
 '.local',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.ollama',
 '.openjfx',
 '.p2',
 '.packettracer',
 '.redhat',
 '.skiko',
 '.streamlit',
 '.viminfo',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 'airflow',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'C',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'downloadtemp',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'gabung_modis_2019_2024.ipynb',
 'int main(){.c',
 'int main(){.cpp',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TM.blf',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'output',
 'Pictures',
 'pipx',
 'Postman',
 'PRAK001_2310817310014_MUHAMMADRIZKISAPUTRA.py',
 "print('Hello World').py",
 "print('Muhammad Rizki Saputra_2310817310014').py",
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Tugas_Praktikum_Pemprogramman',
 'Ubisoft Game Launcher',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Videos',
 'VirtualBox VMs',
 'WPS Cloud Files']

In [5]:
import pandas as pd

path = r"C:\Users\ASUS TUF\Downloads\data\Rat_Sightings.csv"
df = pd.read_csv(path, low_memory=False)

In [6]:
df.shape
df.head(3)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,31464015,09/04/2015 12:00:00 AM,09/18/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Mixed Use Building,10006.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.707772,-74.012963,"(40.70777155363643, -74.01296309970473)"
1,31464024,09/04/2015 12:00:00 AM,10/28/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Commercial Building,10306.0,2270 HYLAN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.575209,-74.104547,"(40.575209242947444, -74.1045465185469)"
2,31464025,09/04/2015 12:00:00 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,10310.0,758 POST AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.631236,-74.126878,"(40.63123555151668, -74.12687759748677)"

In [7]:
df["Created Date"] = pd.to_datetime(df["Created Date"], errors="coerce")
df["Closed Date"] = pd.to_datetime(df["Closed Date"], errors="coerce")

C:\Users\ASUS TUF\AppData\Local\Temp\ipykernel_17864\4278419671.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Created Date"] = pd.to_datetime(df["Created Date"], errors="coerce")
C:\Users\ASUS TUF\AppData\Local\Temp\ipykernel_17864\4278419671.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Closed Date"] = pd.to_datetime(df["Closed Date"], errors="coerce")

In [1]:
df[["Created Date","Closed Date"]].dtypes
df[["Created Date","Closed Date"]].head(5)
df[["Created Date","Closed Date"]].isna().mean()*100

NameError: name 'df' is not defined

In [2]:
import pandas as pd

path = r"C:\Users\ASUS TUF\Downloads\data\Rat_Sightings.csv"
df = pd.read_csv(path, low_memory=False)

df.shape
df.head(3)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,31464015,09/04/2015 12:00:00 AM,09/18/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Mixed Use Building,10006.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.707772,-74.012963,"(40.70777155363643, -74.01296309970473)"
1,31464024,09/04/2015 12:00:00 AM,10/28/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Commercial Building,10306.0,2270 HYLAN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.575209,-74.104547,"(40.575209242947444, -74.1045465185469)"
2,31464025,09/04/2015 12:00:00 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,10310.0,758 POST AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.631236,-74.126878,"(40.63123555151668, -74.12687759748677)"

In [3]:
fmt = "%m/%d/%Y %I:%M:%S %p"
df["Created Date"] = pd.to_datetime(df["Created Date"], format=fmt, errors="coerce")
df["Closed Date"]  = pd.to_datetime(df["Closed Date"],  format=fmt, errors="coerce")

In [4]:
df[["Created Date","Closed Date"]].dtypes
df[["Created Date","Closed Date"]].head(5)
(df[["Created Date","Closed Date"]].isna().mean()*100)

Created Date     0.00000
Closed Date     10.72571
dtype: float64

In [5]:
"df" in globals()

True

In [6]:
df["resolution_time_hours"] = (df["Closed Date"] - df["Created Date"]).dt.total_seconds() / 3600
df["resolution_time_hours"].head()

0     336.0
1    1296.0
2       NaN
3     240.0
4     432.0
Name: resolution_time_hours, dtype: float64

In [7]:
df["resolution_time_hours"].describe()

count    9.098300e+04
mean     1.012944e+02
std      6.827468e+03
min     -1.028928e+06
25%      4.153250e+01
50%      1.680000e+02
75%      3.600000e+02
max      1.363200e+04
Name: resolution_time_hours, dtype: float64

In [8]:
df_clean = df.dropna(subset=["Closed Date"]).copy()

In [9]:
df_clean = df_clean[df_clean["resolution_time_hours"] > 0].copy()

In [10]:
print("Awal:", df.shape)
print("Setelah drop Closed Date NaN + durasi <=0:", df_clean.shape)
df_clean["resolution_time_hours"].describe(percentiles=[0.5, 0.9, 0.95, 0.99, 0.995])print("Awal:", df.shape)
print("Setelah drop Closed Date NaN + durasi <=0:", df_clean.shape)
df_clean["resolution_time_hours"].describe(percentiles=[0.5, 0.9, 0.95, 0.99, 0.995])

SyntaxError: invalid syntax (1181221649.py, line 3)

In [11]:
print("Awal:", df.shape)
print("Setelah drop Closed Date NaN + durasi <=0:", df_clean.shape)

df_clean["resolution_time_hours"].describe(percentiles=[0.5, 0.9, 0.95, 0.99, 0.995])

Awal: (101914, 53)
Setelah drop Closed Date NaN + durasi <=0: (72418, 53)

count    72418.000000
mean       376.358036
std        576.329741
min          0.314722
50%        216.000000
90%        777.756639
95%       1152.000000
99%       2480.454011
99.5%     3501.960000
max      13632.000000
Name: resolution_time_hours, dtype: float64

In [12]:
print("Awal:", df.shape)
print("Setelah drop Closed Date NaN + durasi <=0:", df_clean.shape)

desc = df_clean["resolution_time_hours"].describe(percentiles=[0.5, 0.9, 0.95, 0.99, 0.995])
desc.round(2)

Awal: (101914, 53)
Setelah drop Closed Date NaN + durasi <=0: (72418, 53)

count    72418.00
mean       376.36
std        576.33
min          0.31
50%        216.00
90%        777.76
95%       1152.00
99%       2480.45
99.5%     3501.96
max      13632.00
Name: resolution_time_hours, dtype: float64

In [13]:
cap = df_clean["resolution_time_hours"].quantile(0.995)
df_clean["y"] = df_clean["resolution_time_hours"].clip(upper=cap)

cap

np.float64(3501.9599999998463)

In [14]:
cd = df_clean["Created Date"]
df_clean["created_year"] = cd.dt.year
df_clean["created_month"] = cd.dt.month
df_clean["created_day"] = cd.dt.day
df_clean["created_dayofweek"] = cd.dt.dayofweek
df_clean["created_hour"] = cd.dt.hour
df_clean["is_weekend"] = (df_clean["created_dayofweek"] >= 5).astype(int)

In [15]:
drop_cols = [
    "Complaint Type", "Descriptor",
    "Created Date", "Closed Date",
    "Due Date", "Resolution Action Updated Date"
]
df_clean = df_clean.drop(columns=drop_cols, errors="ignore")

In [16]:
df_clean.columns.tolist()

['Unique Key',
 'Agency',
 'Agency Name',
 'Location Type',
 'Incident Zip',
 'Incident Address',
 'Street Name',
 'Cross Street 1',
 'Cross Street 2',
 'Intersection Street 1',
 'Intersection Street 2',
 'Address Type',
 'City',
 'Landmark',
 'Facility Type',
 'Status',
 'Community Board',
 'Borough',
 'X Coordinate (State Plane)',
 'Y Coordinate (State Plane)',
 'Park Facility Name',
 'Park Borough',
 'School Name',
 'School Number',
 'School Region',
 'School Code',
 'School Phone Number',
 'School Address',
 'School City',
 'School State',
 'School Zip',
 'School Not Found',
 'School or Citywide Complaint',
 'Vehicle Type',
 'Taxi Company Borough',
 'Taxi Pick Up Location',
 'Bridge Highway Name',
 'Bridge Highway Direction',
 'Road Ramp',
 'Bridge Highway Segment',
 'Garage Lot Name',
 'Ferry Direction',
 'Ferry Terminal Name',
 'Latitude',
 'Longitude',
 'Location',
 'resolution_time_hours',
 'y',
 'created_year',
 'created_month',
 'created_day',
 'created_dayofweek',
 'created_hour',
 'is_weekend']

In [17]:
cap = df_clean["resolution_time_hours"].quantile(0.995)
df_clean["y"] = df_clean["resolution_time_hours"].clip(upper=cap)
cap

np.float64(3501.9599999998463)

In [18]:
df_clean["y"].describe()

count    72418.000000
mean       364.281143
std        453.984310
min          0.314722
25%        120.000000
50%        216.000000
75%        432.000000
max       3501.960000
Name: y, dtype: float64

In [19]:
[c for c in ["created_year","created_month","created_dayofweek","created_hour","is_weekend"] if c not in df_clean.columns]

[]

In [20]:
feature_cols = [
    "created_year", "created_month", "created_dayofweek", "created_hour", "is_weekend",
    "Borough", "Community Board", "Incident Zip", "City",
    "Location Type", "Address Type",
    "Latitude", "Longitude"
]

X = df_clean[feature_cols].copy()
y = df_clean["y"].copy()

X.shape, y.shape

((72418, 13), (72418,))

In [21]:
X["Incident Zip"] = X["Incident Zip"].astype(str)
X["Incident Zip"] = X["Incident Zip"].str.replace(r"\.0$", "", regex=True)
X["Incident Zip"] = X["Incident Zip"].replace(["nan", "NaN", "<NA>"], "Unknown")
X["Incident Zip"] = X["Incident Zip"].fillna("Unknown")

In [22]:
def topk_other(series, k=30, other_label="Other"):
    series = series.fillna("Unknown").astype(str)
    top = series.value_counts().head(k).index
    return series.where(series.isin(top), other_label)

X["Incident Zip"] = topk_other(X["Incident Zip"], k=30)
X["Community Board"] = topk_other(X["Community Board"], k=30)
X["City"] = topk_other(X["City"], k=30)

In [23]:
(X.isna().mean()*100).sort_values(ascending=False).head(15)

Latitude             0.770527
Longitude            0.770527
Address Type         0.379740
created_year         0.000000
created_month        0.000000
created_dayofweek    0.000000
created_hour         0.000000
is_weekend           0.000000
Borough              0.000000
Community Board      0.000000
Incident Zip         0.000000
City                 0.000000
Location Type        0.000000
dtype: float64

In [24]:
df_model = X.copy()
df_model["y"] = y
df_model.to_csv("modeling_ready.csv", index=False)

In [25]:
X["Incident Zip"].value_counts().head(35)

Incident Zip
Other    40471
11221     2431
11216     1725
11233     1480
11238     1479
10025     1309
11207     1298
11385     1243
10456     1165
10467     1117
11213     1070
11217     1061
10457     1034
11206     1026
11211     1026
11226     1013
11215      994
10458      979
11237      974
10027      929
10128      885
11212      830
10002      826
10031      795
10024      780
10453      778
11208      777
10026      751
10009      743
11203      716
10452      713
Name: count, dtype: int64

In [26]:
import os
os.getcwd()
os.listdir(".")

['-1.14-windows.xml',
 '.anaconda',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.copilot',
 '.docker',
 '.eclipse',
 '.emulator_console_auth_token',
 '.gemini',
 '.git',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.Ld9VirtualBox',
 '.lesshst',
 '.local',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.ollama',
 '.openjfx',
 '.p2',
 '.packettracer',
 '.redhat',
 '.skiko',
 '.streamlit',
 '.viminfo',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 'airflow',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'C',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'downloadtemp',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'gabung_modis_2019_2024.ipynb',
 'int main(){.c',
 'int main(){.cpp',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'modeling_ready.csv',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TM.blf',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d4cc477d-cbd8-11ef-b8d7-bae1a8b7a8bf}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'output',
 'Pictures',
 'pipx',
 'Postman',
 'PRAK001_2310817310014_MUHAMMADRIZKISAPUTRA.py',
 "print('Hello World').py",
 "print('Muhammad Rizki Saputra_2310817310014').py",
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Tugas_Praktikum_Pemprogramman',
 'Ubisoft Game Launcher',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Videos',
 'VirtualBox VMs',
 'WPS Cloud Files']

In [27]:
df_model.to_csv(r"C:\Users\ASUS TUF\Downloads\data\modeling_ready.csv", index=False)

In [28]:
X.shape, y.shape

((72418, 13), (72418,))

In [29]:
# 1) kategorikal -> Unknown
cat_cols = ["Borough", "Community Board", "Incident Zip", "City", "Location Type", "Address Type"]
for c in cat_cols:
    X[c] = X[c].fillna("Unknown").astype(str)

# 2) numerik -> median
num_cols = ["Latitude", "Longitude"]
for c in num_cols:
    X[c] = X[c].fillna(X[c].median())

In [30]:
X.isna().sum().sort_values(ascending=False).head(10)

created_year         0
created_month        0
created_dayofweek    0
created_hour         0
is_weekend           0
Borough              0
Community Board      0
Incident Zip         0
City                 0
Location Type        0
dtype: int64

In [31]:
X.isna().sum().sum()

np.int64(0)

In [32]:
X.isna().sum()[X.isna().sum() > 0]

Series([], dtype: int64)

In [33]:
df_model = X.copy()
df_model["y"] = y
df_model.to_csv("modeling_ready.csv", index=False)

In [34]:
import pandas as pd
df_check = pd.read_csv("modeling_ready.csv")
df_check.isna().sum().sum()

np.int64(0)

In [35]:
import os, time

path = "modeling_ready.csv"
print("Last modified (epoch):", os.path.getmtime(path))
print("Last modified (readable):", time.ctime(os.path.getmtime(path)))
print("File size (bytes):", os.path.getsize(path))

Last modified (epoch): 1771954633.9750335
Last modified (readable): Wed Feb 25 01:37:13 2026
File size (bytes): 9038944

In [36]:
import pandas as pd

df_check = pd.read_csv("modeling_ready.csv")
print(df_check.shape)
print("Total NaN:", df_check.isna().sum().sum())
print(df_check.head(2))

(72418, 14)
Total NaN: 0
   created_year  created_month  created_dayofweek  created_hour  is_weekend  \
0          2015              9                  4             0           0
1          2015              9                  4             0           0

         Borough Community Board Incident Zip           City  \
0      MANHATTAN           Other        Other       NEW YORK
1  STATEN ISLAND           Other        Other  STATEN ISLAND

                  Location Type  Address Type   Latitude  Longitude       y
0  3+ Family Mixed Use Building  INTERSECTION  40.707772 -74.012963   336.0
1           Commercial Building       LATLONG  40.575209 -74.104547  1296.0

In [37]:
import os
os.path.abspath("modeling_ready.csv")

'C:\\Users\\ASUS TUF\\modeling_ready.csv'

In [38]:
print("RAW shape:", df.shape)
print("CLEAN shape:", df_clean.shape)
print("Dropped rows:", df.shape[0] - df_clean.shape[0])

print("\nClosed Date missing % (raw):", round(df["Closed Date"].isna().mean()*100, 2))
print("Total NaN in modeling_ready:", int((X.isna().sum().sum())))
print("y cap (p99.5):", round(cap, 2))

RAW shape: (101914, 53)
CLEAN shape: (72418, 54)
Dropped rows: 29496

Closed Date missing % (raw): 10.73
Total NaN in modeling_ready: 0
y cap (p99.5): 3501.96

In [41]:
# BEFORE (raw)
print("RAW shape:", df.shape)
display(df.head(3))

cols_check = ["Created Date", "Closed Date", "Incident Zip", "Borough", "City", "Latitude", "Longitude"]
miss_raw = (df[cols_check].isna().mean()*100).round(2)
print("\nRAW missing % (key cols):")
display(miss_raw)

RAW shape: (101914, 53)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location,resolution_time_hours
0,31464015,2015-09-04,2015-09-18,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Mixed Use Building,10006.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.707772,-74.012963,"(40.70777155363643, -74.01296309970473)",336.0
1,31464024,2015-09-04,2015-10-28,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Commercial Building,10306.0,2270 HYLAN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,40.575209,-74.104547,"(40.575209242947444, -74.1045465185469)",1296.0
2,31464025,2015-09-04,NaT,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,10310.0,758 POST AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,40.631236,-74.126878,"(40.63123555151668, -74.12687759748677)",NaN

RAW missing % (key cols):

Created Date     0.00
Closed Date     10.73
Incident Zip     0.33
Borough          0.00
City             0.34
Latitude         0.69
Longitude        0.69
dtype: float64

In [42]:
# AFTER (clean)
print("CLEAN shape:", df_clean.shape)
display(df_clean.head(3))

print("\nTarget y summary:")
display(df_clean["y"].describe().round(2))

df_model = X.copy()
df_model["y"] = y
print("\nMODELING READY shape:", df_model.shape)
print("Total NaN in modeling ready:", int(df_model.isna().sum().sum()))
display(df_model.head(3))

CLEAN shape: (72418, 54)

,Unique Key,Agency,Agency Name,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,...,Longitude,Location,resolution_time_hours,y,created_year,created_month,created_day,created_dayofweek,created_hour,is_weekend
0,31464015,DOHMH,Department of Health and Mental Hygiene,3+ Family Mixed Use Building,10006.0,NaN,NaN,NaN,NaN,TRINITY PLACE,...,-74.012963,"(40.70777155363643, -74.01296309970473)",336.0,336.0,2015,9,4,4,0,0
1,31464024,DOHMH,Department of Health and Mental Hygiene,Commercial Building,10306.0,2270 HYLAN BOULEVARD,HYLAN BOULEVARD,NaN,NaN,NaN,...,-74.104547,"(40.575209242947444, -74.1045465185469)",1296.0,1296.0,2015,9,4,4,0,0
3,31464026,DOHMH,Department of Health and Mental Hygiene,3+ Family Apt. Building,11206.0,198 SCHOLES STREET,SCHOLES STREET,HUMBOLDT STREET,BUSHWICK AVENUE,NaN,...,-73.941207,"(40.70898692345805, -73.94120690238431)",240.0,240.0,2015,9,4,4,0,0

Target y summary:

count    72418.00
mean       364.28
std        453.98
min          0.31
25%        120.00
50%        216.00
75%        432.00
max       3501.96
Name: y, dtype: float64

MODELING READY shape: (72418, 14)
Total NaN in modeling ready: 0

,created_year,created_month,created_dayofweek,created_hour,is_weekend,Borough,Community Board,Incident Zip,City,Location Type,Address Type,Latitude,Longitude,y
0,2015,9,4,0,0,MANHATTAN,Other,Other,NEW YORK,3+ Family Mixed Use Building,INTERSECTION,40.707772,-74.012963,336.0
1,2015,9,4,0,0,STATEN ISLAND,Other,Other,STATEN ISLAND,Commercial Building,LATLONG,40.575209,-74.104547,1296.0
3,2015,9,4,0,0,BROOKLYN,01 BROOKLYN,11206,BROOKLYN,3+ Family Apt. Building,ADDRESS,40.708987,-73.941207,240.0

In [43]:
import numpy as np

print("=== BEFORE (RAW) ===")
print("RAW shape:", df.shape)
print("Closed Date missing % (raw):", round(df["Closed Date"].isna().mean()*100, 2))

print("\n=== AFTER (CLEAN) ===")
print("CLEAN shape:", df_clean.shape)
print("Dropped rows:", df.shape[0] - df_clean.shape[0])

print("\nTarget y info (after):")
print("y cap (p99.5):", round(cap, 2))
print("y max:", round(df_clean["y"].max(), 2))

print("\n=== MODELING READY ===")
df_model = X.copy()
df_model["y"] = y
print("MODELING READY shape:", df_model.shape)
print("Total NaN in modeling_ready:", int(df_model.isna().sum().sum()))

print("\nSample rows (modeling_ready head):")
display(df_model.head(2))

=== BEFORE (RAW) ===
RAW shape: (101914, 53)
Closed Date missing % (raw): 10.73

=== AFTER (CLEAN) ===
CLEAN shape: (72418, 54)
Dropped rows: 29496

Target y info (after):
y cap (p99.5): 3501.96
y max: 3501.96

=== MODELING READY ===
MODELING READY shape: (72418, 14)
Total NaN in modeling_ready: 0

Sample rows (modeling_ready head):

,created_year,created_month,created_dayofweek,created_hour,is_weekend,Borough,Community Board,Incident Zip,City,Location Type,Address Type,Latitude,Longitude,y
0,2015,9,4,0,0,MANHATTAN,Other,Other,NEW YORK,3+ Family Mixed Use Building,INTERSECTION,40.707772,-74.012963,336.0
1,2015,9,4,0,0,STATEN ISLAND,Other,Other,STATEN ISLAND,Commercial Building,LATLONG,40.575209,-74.104547,1296.0

In [44]:
df_clean[["resolution_time_hours","y"]].head()
df_clean[["resolution_time_hours","y"]].describe()

       resolution_time_hours             y
count           72418.000000  72418.000000
mean              376.358036    364.281143
std               576.329741    453.984310
min                 0.314722      0.314722
25%               120.000000    120.000000
50%               216.000000    216.000000
75%               432.000000    432.000000
max             13632.000000   3501.960000

In [45]:
df_check = pd.read_csv("modeling_ready.csv")
len(df_check.columns) - 1

13

In [46]:
print("Jumlah fitur:", X.shape[1])
print("Daftar fitur:", X.columns.tolist())

Jumlah fitur: 13
Daftar fitur: ['created_year', 'created_month', 'created_dayofweek', 'created_hour', 'is_weekend', 'Borough', 'Community Board', 'Incident Zip', 'City', 'Location Type', 'Address Type', 'Latitude', 'Longitude']

In [47]:
import pandas as pd
df_check = pd.read_csv("modeling_ready.csv")
df_check.columns

Index(['created_year', 'created_month', 'created_dayofweek', 'created_hour',
       'is_weekend', 'Borough', 'Community Board', 'Incident Zip', 'City',
       'Location Type', 'Address Type', 'Latitude', 'Longitude', 'y'],
      dtype='object')

In [48]:
import pandas as pd

df_check = pd.read_csv("modeling_ready.csv")
print("Kolom:", df_check.columns.tolist())
print("Apakah ada y?", "y" in df_check.columns)
df_check[["y"]].head()

Kolom: ['created_year', 'created_month', 'created_dayofweek', 'created_hour', 'is_weekend', 'Borough', 'Community Board', 'Incident Zip', 'City', 'Location Type', 'Address Type', 'Latitude', 'Longitude', 'y']
Apakah ada y? True

        y
0   336.0
1  1296.0
2   240.0
3   432.0
4   432.0